// AUTOGENERATED FILE; see /Users/crystal/weibo/dockerf/src/github.com/docker/docker/hack/make/.go-autogen
package dockerversion

var (
	GITCOMMIT string = "d12ea79"
	VERSION   string = "1.8.1"
	BUILDTIME string = "Sun Aug 16 12:43:23 UTC 2015"

	IAMSTATIC string = "false"
	INITSHA1  string = ""
	INITPATH  string = ""
)
