// AUTOGENERATED FILE; see /data/go/src/github.com/docker/docker/hack/make/.go-autogen
package dockerversion

var (
	GITCOMMIT string = "0baf609"
	VERSION   string = "1.7.0"

	IAMSTATIC string = "false"
	INITSHA1  string = ""
	INITPATH  string = ""
)
